"""Built-in machine templates inspired by ModTweaker logger output."""
from dataclasses import dataclass
from typing import Dict, List


RECIPE_MAPS = [
    "gt.recipe.orewasher",
    "gt.recipe.thermalcentrifuge",
    "gt.recipe.compressor",
    "gt.recipe.extractor",
    "ic.recipe.recycler",
    "mc.recipe.furnace",
    "gt.recipe.microwave",
    "gt.recipe.scanner",
    "gt.recipe.rockbreaker",
    "gt.recipe.byproductlist",
    "gt.recipe.replicator",
    "gt.recipe.fakeAssemblylineProcess",
    "gt.recipe.plasmaarcfurnace",
    "gt.recipe.arcfurnace",
    "gt.recipe.printer",
    "gt.recipe.sifter",
    "gt.recipe.press",
    "gt.recipe.laserengraver",
    "gt.recipe.mixer",
    "gt.recipe.autoclave",
    "gt.recipe.electromagneticseparator",
    "gt.recipe.polarizer",
    "gt.recipe.macerator",
    "gt.recipe.chemicalbath",
    "gt.recipe.fluidcanner",
    "gt.recipe.brewer",
    "gt.recipe.fluidheater",
    "gt.recipe.distillery",
    "gt.recipe.fermenter",
    "gt.recipe.fluidsolidifier",
    "gt.recipe.fluidextractor",
    "gt.recipe.packager",
    "gt.recipe.unpackager",
    "gt.recipe.fusionreactor",
    "gt.recipe.complexfusionreactor",
    "gt.recipe.centrifuge",
    "gt.recipe.electrolyzer",
    "gt.recipe.blastfurnace",
    "gt.recipe.plasmaforge",
    "gt.recipe.transcendentplasmamixerrecipes",
    "gt.recipe.fakespaceprojects",
    "gt.recipe.primitiveblastfurnace",
    "gt.recipe.implosioncompressor",
    "gt.recipe.vacuumfreezer",
    "gt.recipe.chemicalreactor",
    "gt.recipe.largechemicalreactor",
    "gt.recipe.distillationtower",
    "gt.recipe.craker",
    "gt.recipe.pyro",
    "gt.recipe.wiremill",
    "gt.recipe.metalbender",
    "gt.recipe.alloysmelter",
    "gt.recipe.assembler",
    "gt.recipe.circuitassembler",
    "gt.recipe.canner",
    "gt.recipe.cncmachine",
    "gt.recipe.lathe",
    "gt.recipe.cuttingsaw",
    "gt.recipe.slicer",
    "gt.recipe.extruder",
    "gt.recipe.hammer",
    "gt.recipe.uuamplifier",
    "gt.recipe.massfab",
    "gt.recipe.dieselgeneratorfuel",
    "gt.recipe.extremedieselgeneratorfuel",
    "gt.recipe.gasturbinefuel",
    "gt.recipe.thermalgeneratorfuel",
    "gt.recipe.semifluidboilerfuels",
    "gt.recipe.plasmageneratorfuels",
    "gt.recipe.magicfuels",
    "gt.recipe.smallnaquadahreactor",
    "gt.recipe.largenaquadahreactor",
    "gt.recipe.fluidnaquadahreactor",
    "gt.recipe.hugenaquadahreactor",
    "gt.recipe.extrahugenaquadahreactor",
    "gt.recipe.fluidfuelnaquadahreactor",
    "gt.recipe.largeelectrolyzer",
    "gt.recipe.largecentrifuge",
    "gt.recipe.largemixer",
    "gt.recipe.largeboilerfakefuels",
    "gt.recipe.nanoforge",
    "gt.recipe.pcbfactory",
    "gt.recipe.ic2nuke",
    "gtpp.recipe.cokeoven",
    "gtpp.recipe.matterfab2",
    "gtpp.recipe.rocketenginefuel",
    "gtpp.recipe.quantumforcesmelter",
    "gtpp.recipe.geothermalfuel",
    "gtpp.recipe.chemicaldehydrator",
    "gtpp.recipe.vacfurnace",
    "gtpp.recipe.alloyblastsmelter",
    "gtpp.recipe.steamturbinefuel",
    "gtpp.recipe.lftr",
    "gtpp.recipe.nuclearsaltprocessingplant",
    "gtpp.recipe.oremill",
    "gtpp.recipe.fissionfuel",
    "gtpp.recipe.coldtrap",
    "gtpp.recipe.reactorprocessingunit",
    "gtpp.recipe.simplewasher",
    "gtpp.recipe.moleculartransformer",
    "gtpp.recipe.elementaldupe",
    "gtpp.recipe.fluidchemicaleactor",
    "gtpp.recipe.RTGgenerators",
    "gtpp.recipe.thermalgeneratorfuel",
    "gtpp.recipe.solartower",
    "gtpp.recipe.cyclotron",
    "gtpp.recipe.slowfusionreactor",
    "gtpp.recipe.componentassembler",
    "gtpp.recipe.fishpond",
    "gtpp.recipe.spargetower",
    "gtpp.recipe.cryogenicfreezer",
    "gtpp.recipe.multicentrifuge",
    "gtpp.recipe.multielectro",
    "gtpp.recipe.temp4",
    "gtpp.recipe.multimixer",
    "gtpp.recipe.multidehydrator",
    "gtpp.recipe.semifluidgeneratorfuels",
    "gtpp.recipe.flotationcell",
    "gtpp.recipe.treefarm",
    "bw.recipe.biolab",
    "bw.recipe.BacteriaVat",
    "bw.fuels.acidgens",
    "bw.recipe.cal",
    "bw.recipe.radhatch",
    "bw.recipe.htgr",
    "emt.recipe.fusioncrafting",
    "gg.recipe.naquadah_reactor",
    "gg.recipe.naquadah_fuel_refine_factory",
    "gg.recipe.neutron_activator",
    "gg.recipe.extreme_heat_exchanger",
    "gg.recipe.precise_assembler",
    "gg.recipe.componentassemblyline",
    "gt.recipe.fakerockbreaker",
    "gt.recipe.spaceResearch",
    "gt.recipe.spaceAssembler",
    "gt.recipe.spaceMining",
    "gt.recipe.eyeofharmony",
    "gt.recipe.researchStation",
    "gt.recipe.em_scanner",
    "gtnhlanth.recipe.digester",
    "gtnhlanth.recipe.disstank",
    "gt.recipe.electricimplosioncompressor",
]


@dataclass(frozen=True)
class MachineTemplate:
    template_id: str
    display_name: str
    max_item_inputs: int
    max_item_outputs: int
    max_fluid_inputs: int
    max_fluid_outputs: int
    style: str
    recipe_map: str = ""


TEMPLATES: Dict[str, MachineTemplate] = {
    "generic_gt_machine": MachineTemplate(
        "generic_gt_machine",
        "Generic GT Machine",
        16,
        4,
        4,
        4,
        "generic_gt",
        "gt.recipe.assembler",
    ),
    "assembler_like": MachineTemplate("assembler_like", "Assembler-like", 16, 4, 4, 4, "generic_gt", "gt.recipe.assembler"),
    "cutter_like": MachineTemplate("cutter_like", "Cutter-like", 16, 4, 4, 4, "generic_gt", "gt.recipe.cuttingsaw"),
    "macerator_like": MachineTemplate("macerator_like", "Macerator-like", 16, 4, 4, 4, "generic_gt", "gt.recipe.macerator"),
    "mixer_like": MachineTemplate("mixer_like", "Mixer-like", 16, 4, 4, 4, "generic_gt", "gt.recipe.mixer"),
    "chemical_reactor_like": MachineTemplate(
        "chemical_reactor_like",
        "Chemical Reactor-like",
        16,
        4,
        4,
        4,
        "generic_gt",
        "gt.recipe.chemicalreactor",
    ),
    "blast_furnace_like": MachineTemplate(
        "blast_furnace_like",
        "Blast Furnace-like",
        16,
        4,
        4,
        4,
        "generic_gt",
        "gt.recipe.blastfurnace",
    ),
    "thermal_expansion_furnace": MachineTemplate(
        "thermal_expansion_furnace",
        "Thermal Expansion Furnace",
        1,
        1,
        0,
        0,
        "te_furnace",
    ),
    "thermal_expansion_pulverizer": MachineTemplate(
        "thermal_expansion_pulverizer",
        "Thermal Expansion Pulverizer",
        1,
        2,
        0,
        0,
        "te_pulverizer",
    ),
    "appeng_grinder": MachineTemplate("appeng_grinder", "AE Grinder", 1, 3, 0, 0, "ae_grinder"),
    "appeng_inscriber": MachineTemplate("appeng_inscriber", "AE Inscriber", 3, 1, 0, 0, "ae_inscriber"),
}


def template_options() -> List[MachineTemplate]:
    return list(TEMPLATES.values())


def recipe_map_options() -> List[str]:
    return list(RECIPE_MAPS)
